// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo_Role int32

const (
	UserInfo_REGULAR UserInfo_Role = 0
	UserInfo_ADMIN   UserInfo_Role = 1
)

var UserInfo_Role_name = map[int32]string{
	0: "REGULAR",
	1: "ADMIN",
}

var UserInfo_Role_value = map[string]int32{
	"REGULAR": 0,
	"ADMIN":   1,
}

func (x UserInfo_Role) String() string {
	return proto.EnumName(UserInfo_Role_name, int32(x))
}

func (UserInfo_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1, 0}
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type UserInfo struct {
	Password             []byte        `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Admin                bool          `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Role                 UserInfo_Role `protobuf:"varint,3,opt,name=role,proto3,enum=users.UserInfo_Role" json:"role,omitempty"`
	Directories          []string      `protobuf:"bytes,4,rep,name=directories,proto3" json:"directories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *UserInfo) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *UserInfo) GetRole() UserInfo_Role {
	if m != nil {
		return m.Role
	}
	return UserInfo_REGULAR
}

func (m *UserInfo) GetDirectories() []string {
	if m != nil {
		return m.Directories
	}
	return nil
}

type Session struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetDirectoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoriesRequest) Reset()         { *m = GetDirectoriesRequest{} }
func (m *GetDirectoriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDirectoriesRequest) ProtoMessage()    {}
func (*GetDirectoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *GetDirectoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoriesRequest.Unmarshal(m, b)
}
func (m *GetDirectoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoriesRequest.Marshal(b, m, deterministic)
}
func (m *GetDirectoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoriesRequest.Merge(m, src)
}
func (m *GetDirectoriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDirectoriesRequest.Size(m)
}
func (m *GetDirectoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoriesRequest proto.InternalMessageInfo

type GetDirectoriesResponse struct {
	Directories          string   `protobuf:"bytes,1,opt,name=directories,proto3" json:"directories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectoriesResponse) Reset()         { *m = GetDirectoriesResponse{} }
func (m *GetDirectoriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDirectoriesResponse) ProtoMessage()    {}
func (*GetDirectoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *GetDirectoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectoriesResponse.Unmarshal(m, b)
}
func (m *GetDirectoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectoriesResponse.Marshal(b, m, deterministic)
}
func (m *GetDirectoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectoriesResponse.Merge(m, src)
}
func (m *GetDirectoriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDirectoriesResponse.Size(m)
}
func (m *GetDirectoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectoriesResponse proto.InternalMessageInfo

func (m *GetDirectoriesResponse) GetDirectories() string {
	if m != nil {
		return m.Directories
	}
	return ""
}

func init() {
	proto.RegisterEnum("users.UserInfo_Role", UserInfo_Role_name, UserInfo_Role_value)
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*UserInfo)(nil), "users.UserInfo")
	proto.RegisterType((*Session)(nil), "users.Session")
	proto.RegisterType((*GetDirectoriesRequest)(nil), "users.GetDirectoriesRequest")
	proto.RegisterType((*GetDirectoriesResponse)(nil), "users.GetDirectoriesResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x4e, 0xe3, 0x40,
	0x10, 0x85, 0xa7, 0x1d, 0x7b, 0x92, 0x94, 0x47, 0x56, 0xa6, 0x27, 0x93, 0xf1, 0x58, 0x01, 0xac,
	0x5e, 0x59, 0x2c, 0x62, 0x29, 0xec, 0x22, 0x36, 0x91, 0x82, 0xa2, 0x48, 0x81, 0x45, 0xa3, 0x1c,
	0xc0, 0xe0, 0x26, 0xb4, 0x30, 0x5d, 0xc6, 0xed, 0x88, 0x3d, 0x57, 0xe0, 0x12, 0xec, 0x38, 0x0c,
	0x57, 0xe0, 0x20, 0xc8, 0x3f, 0x80, 0xc3, 0xcf, 0xf2, 0x75, 0xbd, 0xfa, 0xaa, 0x5e, 0xa9, 0xc1,
	0xde, 0x68, 0x91, 0xe9, 0x51, 0x9a, 0x61, 0x8e, 0xd4, 0x2a, 0x85, 0x37, 0x5c, 0x23, 0xae, 0x13,
	0x11, 0x46, 0xa9, 0x0c, 0x23, 0xa5, 0x30, 0x8f, 0x72, 0x89, 0xaa, 0x36, 0xb1, 0x31, 0x98, 0x2b,
	0x2d, 0x32, 0xea, 0x80, 0x21, 0x63, 0x97, 0xf8, 0x24, 0xe8, 0x72, 0x43, 0xc6, 0xd4, 0x83, 0x4e,
	0x1a, 0x69, 0x7d, 0x8b, 0x59, 0xec, 0x1a, 0x3e, 0x09, 0x7e, 0xf1, 0x37, 0xcd, 0x1e, 0x08, 0x74,
	0x8a, 0xa6, 0x85, 0xba, 0xc0, 0x2d, 0x23, 0xd9, 0x36, 0xd2, 0x3e, 0x58, 0x51, 0x7c, 0x2d, 0x55,
	0x49, 0xe8, 0xf0, 0x4a, 0xd0, 0x00, 0xcc, 0x0c, 0x13, 0xe1, 0xb6, 0x7c, 0x12, 0x38, 0xe3, 0xfe,
	0xa8, 0xda, 0xf9, 0x15, 0x38, 0xe2, 0x98, 0x08, 0x5e, 0x3a, 0xa8, 0x0f, 0x76, 0x2c, 0x33, 0x71,
	0x9e, 0x63, 0x26, 0x85, 0x76, 0x4d, 0xbf, 0x15, 0x74, 0x79, 0xf3, 0x89, 0xed, 0x82, 0x59, 0xf8,
	0xa9, 0x0d, 0x6d, 0x7e, 0x34, 0x5f, 0x2d, 0xa7, 0xbc, 0xf7, 0x83, 0x76, 0xc1, 0x9a, 0xce, 0x8e,
	0x17, 0x27, 0x3d, 0xc2, 0xf6, 0xa0, 0x7d, 0x2a, 0xb4, 0x96, 0xa8, 0x8a, 0x65, 0x72, 0xbc, 0x12,
	0xaa, 0x0e, 0x59, 0x09, 0xf6, 0x0f, 0xfe, 0xce, 0x45, 0x3e, 0x7b, 0x47, 0x72, 0x71, 0xb3, 0x11,
	0x3a, 0x67, 0x13, 0x18, 0x7c, 0x2c, 0xe8, 0x14, 0x95, 0xfe, 0xb4, 0x55, 0x85, 0x6b, 0x3e, 0x8d,
	0x1f, 0x09, 0x58, 0x45, 0x1e, 0x4d, 0x2f, 0xc1, 0xd9, 0xa6, 0xd0, 0x61, 0x9d, 0xf7, 0xcb, 0xa9,
	0xde, 0xce, 0x37, 0xd5, 0x6a, 0x34, 0xfb, 0x7f, 0xf7, 0xf4, 0x7c, 0x6f, 0xfc, 0xa1, 0xbf, 0xc3,
	0xc2, 0x16, 0x36, 0x66, 0xd2, 0x43, 0xb0, 0x96, 0xb8, 0x96, 0x8a, 0xda, 0x8d, 0x83, 0x7a, 0x4e,
	0x2d, 0xea, 0x23, 0xb0, 0x41, 0x09, 0xe8, 0x31, 0xbb, 0x02, 0x24, 0x45, 0xc7, 0x84, 0xec, 0x9f,
	0xfd, 0x2c, 0x7f, 0xc3, 0xc1, 0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0xbf, 0x55, 0x29, 0x41,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	// Get a list of user's directories
	//
	// Returns a list of a user's directories.
	GetDirectories(ctx context.Context, in *GetDirectoriesRequest, opts ...grpc.CallOption) (*GetDirectoriesResponse, error)
	// Login and get a session token
	//
	// Checks password and returns a session token to be used in further requests for a user.
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*Session, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetDirectories(ctx context.Context, in *GetDirectoriesRequest, opts ...grpc.CallOption) (*GetDirectoriesResponse, error) {
	out := new(GetDirectoriesResponse)
	err := c.cc.Invoke(ctx, "/users.Users/GetDirectories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/users.Users/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	// Get a list of user's directories
	//
	// Returns a list of a user's directories.
	GetDirectories(context.Context, *GetDirectoriesRequest) (*GetDirectoriesResponse, error)
	// Login and get a session token
	//
	// Checks password and returns a session token to be used in further requests for a user.
	Login(context.Context, *User) (*Session, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) GetDirectories(ctx context.Context, req *GetDirectoriesRequest) (*GetDirectoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectories not implemented")
}
func (*UnimplementedUsersServer) Login(ctx context.Context, req *User) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_GetDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/GetDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetDirectories(ctx, req.(*GetDirectoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectories",
			Handler:    _Users_GetDirectories_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Users_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
